---
- name: Deploy interfaces
  template:
    src: main.conf.j2
    dest: "{{ wg_config_dir }}/{{ prefix }}-{{ ep.inventory_hostname }}.conf"
    owner: root
    group: root
    mode: "0600"
  vars:
    table_id: "{{ range(1000, 65535) | random(seed=ep.host~':'~ep.listen_port) }}"
    private_key: "{{ ep.wg_keys.private_key | default(wg_keys.private) }}"
  loop: "{{ external_endpoints + host_endpoints }}"
  loop_control:
    loop_var: ep
    label: "{{ ep.inventory_hostname }}"
  register: interfaces
  notify:
    - Restart changed interfaces
