---
- name: Get disk space
  set_fact:
    root_mount: "{{ ansible_mounts | selectattr('mount', 'equalto', '/') | list | first }}"
- name: Print disk space
  debug:
    msg: "Filesystem {{ root_mount.device }} : \
       {{ '{:0.2f}'.format(root_mount.size_available / 1024 / 1024 / 1024) }}\
      /{{ '{:0.2f}'.format(root_mount.size_total / 1024 / 1024 / 1024) }} \
      GB"
