- hosts: main
  gather_facts: false
  roles:
    - s3
  tasks:
    - name: Upload wg-easy db
      include_role:
        name: s3
        tasks_from: put
      vars:
        s3_bucket: "main-bucket"
        s3_src: "/root/migration/wg-easy-migrated.db"
        s3_object: "wg-easy.db"
