wg_keys:
  private_ext: ""
  public: ""
  preshared: ""
host: ""
listen_port: ""
peer:
  address4: ""
  address6: ""
  mtu: ":"
amnezia:
  full_config: |
    Jc = 10
    Jmin = 50
    Jmax = 1000
    S1 = 54
    S2 = 82
    H1 = 386695613
    H2 = 1006039112
    H3 = 1867631282
    H4 = 308217490
